// screens/styles.js
import { StyleSheet } from 'react-native';
import { colors, radius, shadow, spacing } from '../theme';

export const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg },
  topBar: { flexDirection: 'row', gap: 10, padding: 14, paddingBottom: 0 },
  bigBtn: {
    borderRadius: radius.pill,
    paddingVertical: 13,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    ...shadow.card,
  },
  btnText: { color: '#fff', fontWeight: '700' },
  sectionTitle: {
    color: colors.sub,
    fontWeight: '700',
    paddingHorizontal: 16,
    paddingTop: 16,
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  empty: { color: colors.faint, textAlign: 'center', marginTop: 40, fontWeight: '600' },
  pageBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 12,
    flexWrap: 'wrap',
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  pageInfo: { color: colors.sub, fontSize: 12.5, fontWeight: '600' },
  pageCtrls: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  pageBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.pill,
    paddingVertical: 7,
    paddingHorizontal: 13,
    backgroundColor: colors.surface,
  },
  pageBtnDisabled: { opacity: 0.45 },
  pageBtnText: { color: colors.primary, fontWeight: '700', fontSize: 12.5 },
  pageBtnTextDisabled: { color: colors.faint },
  pageNum: { color: colors.ink, fontWeight: '700', fontSize: 12.5, minWidth: 68, textAlign: 'center' },
  rowBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.pill,
    paddingVertical: 7,
    paddingHorizontal: 12,
    minWidth: 108,
    minHeight: 30,
    maxWidth: 200,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 12,
    textAlign: 'center',
  },
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  box: {
    backgroundColor: colors.surface,
    borderRadius: radius.sheet,
    padding: 22,
    borderWidth: 1,
    borderColor: colors.border,
    width: '100%',
    maxWidth: 420,
    ...shadow.float,
  },
  boxTitle: { fontSize: 17, fontWeight: '700', color: colors.ink, marginBottom: 12 },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.input,
    backgroundColor: colors.surface,
    padding: 12,
    fontSize: 15,
    marginBottom: 10,
    color: colors.ink,
  },
  typeRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  typeChip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.pill,
    paddingVertical: 8,
    paddingHorizontal: 15,
    backgroundColor: colors.bg,
  },
  typeChipActive: { borderColor: colors.primary, backgroundColor: colors.primarySoft },
  typeText: { color: colors.sub, fontWeight: '600' },
  typeTextActive: { color: colors.primary, fontWeight: '700' },
  bulkBanner: {
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#A7F3D0',
    borderRadius: radius.card,
    margin: 14,
    marginBottom: 0,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bulkBadge: {
    backgroundColor: '#10B981',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  bulkBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '800',
  },
  bulkText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#065F46',
  },
  selectBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
});
